travis:
  secure:
    BINSTAR_TOKEN: NfFXWeCbufQ4PPRlSsnLP+8B+3v86y2KlUkEDbd0xeqwiGSnU3jBHXnt3Q5xzLGOiQeNG30h5f3FUHgCZmTGSATpPh1V5pmSmimIhGQM/crGzpglWeY7VN0tEcYRyvA8N/fnVm/HrI6W3WKwndO5oz+yjfzDPLsakZfSjgbVE/zZX6J4lVQY0BdNG84UKBkSFAcXBD7H1BLrsAt7As9xRdFw/L+dmO4DUSlSzI/RF5766w034DDv2MVWk2bJ73OdfXEMyB4CNICiLLBtp8TA37+nrrHZzxZdUBSIqzEp6xrJ8EW5DpYdozcWBddc/vodzv28+LSlF5ebdV/F4radJkZVOrYjMK3gLaf+Ot6IUYVN+Ed+fDEjnAn44DNTDy6031GqQroIUFxBXP3exuGPH5ANI8EjcItJzAj0Ddx1PbddnQQNyomOlL2ujTarOXcKIH3LBTjz06NOBvJLiK5cXsfmawa1kCT/qkiPuVNjqZ3GCnd2nHhOt+N80+rPMyWSq+S51GjBeqfVZ++KbCfT7te5IHBQKylIwjlSGm/ogoju3ssKTGYZCERJLon0CwoPj5sSMXr7vn0j+H69sFcM/xZVy1Xbw2XP5/05QxYMKCADnJsjrg5z2sMYoD9h+SFsakNDqJS7nMMJHmhjEFV2IhXH5s2N9Xk3GxTkyz+/C08=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
